import type { Metadata } from 'next'
import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: 'Pedro Parente',
  description: 'Generated by create next app',
}

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='px-5 lg:px-16 max-w-7xl mx-auto md:flex gap-10'>
      <Header />
      <main className='w-full my-12 lg:my-24'>
        {children}
      </main>
    </div>
  )
}
